/**
 * Icon category metadata for filtering and organization
 */

export type IconCategory =
  | 'arrows'
  | 'media'
  | 'communication'
  | 'ui'
  | 'files'
  | 'users'
  | 'devices'
  | 'weather'
  | 'tools'
  | 'charts'
  | 'security'
  | 'shopping'
  | 'health'
  | 'education'
  | 'buildings'
  | 'sports'
  | 'food'
  | 'transportation'
  | 'nature'
  | 'social'
  | 'business'
  | 'productivity'
  | 'analytics'
  | 'gaming'
  | 'travel'
  | 'animals'
  | 'furniture'
  | 'clothing'
  | 'shapes'
  | 'text'
  | 'science'
  | 'finance'
  | 'accessibility'
  | 'printing'
  | 'development'
  | 'brands'

export interface IconCategoryInfo {
  id: IconCategory
  label: string
  description: string
}

export const categoryList: IconCategoryInfo[] = [
  { id: 'arrows', label: 'Arrows', description: 'Navigation and directional arrows' },
  { id: 'media', label: 'Media', description: 'Audio, video, and playback controls' },
  { id: 'communication', label: 'Communication', description: 'Messaging, email, and calls' },
  { id: 'ui', label: 'UI', description: 'Interface elements and layout' },
  { id: 'files', label: 'Files', description: 'Documents, folders, and storage' },
  { id: 'users', label: 'Users', description: 'People and accounts' },
  { id: 'devices', label: 'Devices', description: 'Hardware and electronics' },
  { id: 'weather', label: 'Weather', description: 'Weather conditions and climate' },
  { id: 'tools', label: 'Tools', description: 'Hand tools and utilities' },
  { id: 'charts', label: 'Charts', description: 'Basic data visualization' },
  { id: 'security', label: 'Security', description: 'Locks, shields, and privacy' },
  { id: 'shopping', label: 'Shopping', description: 'E-commerce and retail' },
  { id: 'health', label: 'Health', description: 'Medical and wellness' },
  { id: 'education', label: 'Education', description: 'Learning and academics' },
  { id: 'buildings', label: 'Buildings', description: 'Places and architecture' },
  { id: 'sports', label: 'Sports', description: 'Athletics and physical activities' },
  { id: 'food', label: 'Food', description: 'Food and beverages' },
  { id: 'transportation', label: 'Transportation', description: 'Vehicles and travel' },
  { id: 'nature', label: 'Nature', description: 'Plants, landscapes, and environment' },
  { id: 'social', label: 'Social', description: 'Social interactions and emotions' },
  { id: 'business', label: 'Business', description: 'Corporate and professional' },
  { id: 'productivity', label: 'Productivity', description: 'Task management and workflow' },
  { id: 'analytics', label: 'Analytics', description: 'Advanced data analysis and metrics' },
  { id: 'gaming', label: 'Gaming', description: 'Video games and entertainment' },
  { id: 'travel', label: 'Travel', description: 'Tourism and hospitality' },
  { id: 'animals', label: 'Animals', description: 'Wildlife and pets' },
  { id: 'furniture', label: 'Furniture', description: 'Home furnishings and decor' },
  { id: 'clothing', label: 'Clothing', description: 'Fashion and apparel' },
  { id: 'shapes', label: 'Shapes', description: 'Geometric shapes and forms' },
  { id: 'text', label: 'Text', description: 'Typography and text formatting' },
  { id: 'science', label: 'Science', description: 'Scientific and laboratory' },
  { id: 'finance', label: 'Finance', description: 'Banking and money management' },
  { id: 'accessibility', label: 'Accessibility', description: 'Assistive and inclusive design' },
  { id: 'printing', label: 'Printing', description: 'Printers and document output' },
  { id: 'development', label: 'Development', description: 'Programming and software' },
  { id: 'brands', label: 'Brands', description: 'Company and product logos' },
]

/**
 * Icon to category mapping
 * Icons can belong to multiple categories for better discoverability
 */
export const iconCategories: Record<string, IconCategory[]> = {
  // === ARROWS & NAVIGATION ===
  ArrowLeft: ['arrows', 'ui'],
  ArrowRight: ['arrows', 'ui'],
  ArrowUp: ['arrows', 'ui'],
  ArrowDown: ['arrows', 'ui'],
  ArrowUpRight: ['arrows'],
  ArrowUpLeft: ['arrows'],
  ArrowDownRight: ['arrows'],
  ArrowDownLeft: ['arrows'],
  ArrowDownCircle: ['arrows', 'ui'],
  ArrowUpCircle: ['arrows', 'ui'],
  ArrowLeftCircle: ['arrows', 'ui'],
  ArrowRightCircle: ['arrows', 'ui'],
  ArrowDownCircle2: ['arrows', 'ui'],
  ArrowUpCircle2: ['arrows', 'ui'],
  ArrowLeftCircle2: ['arrows', 'ui'],
  ArrowRightCircle2: ['arrows', 'ui'],
  ArrowDownSquare: ['arrows', 'ui'],
  ArrowUpSquare: ['arrows', 'ui'],
  ArrowLeftSquare: ['arrows', 'ui'],
  ArrowRightSquare: ['arrows', 'ui'],
  ChevronDown: ['arrows', 'ui'],
  ChevronUp: ['arrows', 'ui'],
  ChevronsUp: ['arrows'],
  ChevronsDown: ['arrows'],
  ChevronsLeft: ['arrows'],
  ChevronsRight: ['arrows'],
  CornerUpLeft: ['arrows'],
  CornerUpRight: ['arrows'],
  CornerDownLeft: ['arrows'],
  CornerDownRight: ['arrows'],
  CornerUpLeft2: ['arrows'],
  CornerUpRight2: ['arrows'],
  CornerDownLeft2: ['arrows'],
  CornerDownRight2: ['arrows'],
  ArrowsCollapse: ['arrows', 'ui'],
  ArrowsExpand: ['arrows', 'ui'],
  ArrowsMaximize2: ['arrows', 'ui'],
  ArrowsMinimize2: ['arrows', 'ui'],
  MoveHorizontal: ['arrows', 'ui'],
  Navigation: ['arrows', 'transportation'],
  Navigation2: ['arrows', 'transportation'],
  Directions: ['arrows', 'transportation'],
  Route: ['arrows', 'transportation'],
  Waypoints: ['arrows', 'transportation'],

  // === MEDIA & ENTERTAINMENT ===
  Play: ['media'],
  PlayCircle: ['media'],
  Pause: ['media'],
  PauseCircle: ['media'],
  StopCircle: ['media'],
  Volume: ['media'],
  Volume1: ['media'],
  Volume2: ['media'],
  VolumeOff: ['media'],
  VolumeX: ['media'],
  VolumeDial: ['media', 'ui'],
  Mic: ['media', 'communication'],
  MicOff: ['media', 'communication'],
  Camera: ['media', 'devices'],
  CameraMovie: ['media'],
  Airplay: ['media', 'devices'],
  Cast: ['media', 'devices'],
  FastForward: ['media'],
  Film: ['media'],
  Film2: ['media'],
  FilmSlate: ['media'],
  Headphones: ['media', 'devices'],
  Music: ['media'],
  Music2: ['media'],
  Music3: ['media'],
  Music4: ['media'],
  Radio: ['media', 'devices'],
  Repeat: ['media'],
  Rewind: ['media'],
  Shuffle: ['media'],
  SkipBack: ['media'],
  SkipForward: ['media'],
  Speaker: ['media', 'devices'],
  Speaker2: ['media', 'devices'],
  Speaker3: ['media', 'devices'],
  Tv: ['media', 'devices'],
  Video: ['media'],
  Video2: ['media'],
  VideoOff: ['media'],
  Vinyl: ['media'],
  Disc: ['media'],
  Disc2: ['media'],
  Disc3: ['media'],
  Record: ['media'],
  Podcast: ['media', 'communication'],
  Stream: ['media'],
  Live: ['media', 'social'],
  LiveStream: ['media', 'social'],
  Playlist: ['media'],
  Equalizer: ['media'],
  Waveform: ['media'],
  AudioLines: ['media'],
  AudioDescription: ['media', 'accessibility'],
  ClosedCaption: ['media', 'accessibility'],
  ClosedCaptions: ['media', 'accessibility'],
  Subtitle: ['media', 'accessibility'],
  Cinema: ['media', 'buildings'],
  Studio: ['media', 'buildings'],

  // === COMMUNICATION ===
  Mail: ['communication'],
  MailCheck: ['communication'],
  MailOpen: ['communication'],
  MailPlus: ['communication'],
  Mailbox: ['communication'],
  Envelope2: ['communication'],
  MessageCircle: ['communication', 'social'],
  MessageSquare: ['communication', 'social'],
  MessagesSquare: ['communication', 'social'],
  MessageAi: ['communication', 'development'],
  Comment: ['communication', 'social'],
  CommentCheck: ['communication', 'social'],
  CommentPlus: ['communication', 'social'],
  CommentX: ['communication', 'social'],
  Phone: ['communication'],
  PhoneCall: ['communication'],
  PhoneOff: ['communication'],
  PhoneIncoming: ['communication'],
  PhoneOutgoing: ['communication'],
  PhoneMissed: ['communication'],
  Send: ['communication'],
  Send2: ['communication'],
  AtSign: ['communication'],
  Hash: ['communication', 'social'],
  Hashtag: ['communication', 'social'],
  Hashtag2: ['communication', 'social'],
  Voicemail: ['communication'],
  Rss: ['communication'],
  Wifi: ['communication', 'devices'],
  WifiOff: ['communication', 'devices'],
  Broadcast: ['communication', 'media'],
  Inbox: ['communication', 'ui'],
  Contact: ['users', 'communication'],
  Contact2: ['users', 'communication'],
  Mention: ['communication', 'social'],
  Mention2: ['communication', 'social'],
  Bell: ['ui', 'communication'],
  BellOff: ['ui', 'communication'],
  BellRing: ['ui', 'communication'],

  // === UI & LAYOUT ===
  Menu: ['ui'],
  MenuDots: ['ui'],
  MenuDotsHorizontal: ['ui'],
  MenuGrid: ['ui'],
  X: ['ui'],
  Check: ['ui'],
  CheckCircle: ['ui'],
  CheckCircle2: ['ui'],
  CheckSquare: ['ui'],
  Checkbox: ['ui'],
  CheckboxChecked: ['ui'],
  Plus: ['ui'],
  Plus2: ['ui'],
  PlusCircle: ['ui'],
  PlusSquare: ['ui'],
  Minus: ['ui'],
  Minus2: ['ui'],
  MinusCircle: ['ui'],
  MinusSquare: ['ui'],
  XCircle: ['ui'],
  XCircle2: ['ui'],
  XSquare: ['ui'],
  Search: ['ui'],
  SearchPlus: ['ui'],
  SearchMinus: ['ui'],
  Settings: ['ui', 'tools'],
  Filter: ['ui'],
  Grid: ['ui'],
  Grid2x2: ['ui'],
  Grid3x3: ['ui'],
  List: ['ui'],
  Layout: ['ui'],
  LayoutGrid: ['ui'],
  LayoutList: ['ui'],
  Sidebar: ['ui'],
  SidebarOpen: ['ui'],
  SidebarClose: ['ui'],
  PanelLeft: ['ui'],
  PanelRight: ['ui'],
  PanelBottom: ['ui'],
  PanelTop: ['ui'],
  Maximize: ['ui'],
  Minimize: ['ui'],
  Maximize2: ['ui'],
  Minimize2: ['ui'],
  Columns: ['ui'],
  Rows: ['ui'],
  MoreHorizontal: ['ui'],
  Loader: ['ui'],
  Loading: ['ui'],
  Refresh: ['ui'],
  Eye: ['ui'],
  Eye2: ['ui', 'health'],
  EyeOff: ['ui'],
  Copy: ['ui'],
  Bookmark: ['ui'],
  Link: ['ui'],
  ExternalLink: ['ui'],
  ExternalLink2: ['ui'],
  Tag: ['ui', 'shopping'],
  Tag2: ['ui', 'shopping'],
  Tags: ['ui', 'shopping'],
  Zap: ['ui'],
  Info: ['ui'],
  InfoCircle: ['ui'],
  HelpCircle: ['ui'],
  AlertCircle: ['ui'],
  AlertCircle2: ['ui'],
  AlertTriangle: ['ui', 'security'],
  AlertOctagon: ['ui', 'security'],
  Ban: ['ui', 'security'],
  NotAllowed: ['ui', 'security'],
  Clock: ['ui'],
  Calendar: ['ui'],
  CalendarCheck: ['ui', 'productivity'],
  CalendarDays: ['ui'],
  CalendarMinus: ['ui'],
  CalendarPlus: ['ui'],
  CalendarX: ['ui'],
  History: ['ui'],
  Hourglass: ['ui'],
  Timer: ['ui'],
  Stopwatch: ['ui'],
  AlarmClock: ['ui'],
  Toggle: ['ui'],
  ToggleLeft: ['ui'],
  ToggleRight: ['ui'],
  SwitchOn: ['ui'],
  SwitchOff: ['ui'],
  Slider: ['ui'],
  SliderHorizontal: ['ui'],
  SliderVertical: ['ui'],
  RadioButton: ['ui'],
  RadioChecked: ['ui'],
  Sparkles: ['ui'],
  Lightbulb: ['ui', 'education'],
  LightbulbOff: ['ui'],
  Cursor: ['ui'],
  CursorClick: ['ui'],
  CursorText: ['ui'],
  GrabCursor: ['ui'],
  HelpCursor: ['ui'],
  MoveCursor: ['ui'],
  WaitCursor: ['ui'],
  Pointer2: ['ui'],
  Grab: ['ui'],
  Grabbing: ['ui'],
  Pinch: ['ui'],
  PointDown: ['ui'],
  PointLeft: ['ui'],
  PointRight: ['ui'],
  PointUp: ['ui'],
  ResizeDiagonal: ['ui'],
  ResizeHorizontal: ['ui'],
  ResizeVertical: ['ui'],
  Contrast: ['ui'],
  Brightness: ['ui'],
  FocusRing: ['ui'],
  Spotlight: ['ui'],
  Window: ['ui'],
  Window2: ['ui'],
  Progress: ['ui', 'productivity'],
  Queue: ['ui'],
  Pending: ['ui', 'productivity'],
  Complete: ['ui', 'productivity'],
  Incomplete: ['ui', 'productivity'],
  Ok: ['ui'],
  Approved: ['ui', 'business'],
  Rejected: ['ui', 'business'],
  Verified: ['ui', 'security'],
  Verified2: ['ui', 'security'],
  Unverified: ['ui', 'security'],

  // === USERS & PEOPLE ===
  User: ['users'],
  UserCircle: ['users'],
  Users: ['users', 'social'],
  UserPlus: ['users'],
  UserMinus: ['users'],
  UserX: ['users'],
  UserCheck: ['users'],
  UserCog: ['users', 'tools'],
  Baby: ['users'],
  Team: ['users', 'business'],
  Meeting: ['users', 'business'],

  // === SOCIAL & EMOTIONS ===
  Heart: ['social'],
  HeartPulse: ['social', 'health'],
  HeartShape: ['social'],
  Star: ['social', 'ui', 'shapes'],
  ThumbsUp: ['social'],
  ThumbsDown: ['social'],
  Like: ['social'],
  LikeFilled: ['social'],
  Dislike: ['social'],
  Smile: ['social'],
  Frown: ['social'],
  Meh: ['social'],
  Happy: ['social'],
  Sad: ['social'],
  Angry: ['social'],
  Annoyed: ['social'],
  Confused: ['social'],
  Cool: ['social'],
  Cry: ['social'],
  Laugh: ['social'],
  Love: ['social'],
  Peace: ['social'],
  Sleep: ['social'],
  Surprised: ['social'],
  Wink: ['social'],
  Award: ['social', 'sports'],
  Crown: ['social'],
  Gift: ['social', 'shopping'],
  Lively: ['social', 'nature', 'brands'],
  Follow: ['social'],
  Follow2: ['social'],
  Unfollow: ['social'],
  Unfollow2: ['social'],
  Share: ['social'],
  Share2: ['social'],
  ShareForward: ['social'],
  Reaction: ['social'],
  Feed: ['social'],
  Post: ['social'],
  Story: ['social'],
  Repost: ['social'],
  Poll: ['social'],
  Report: ['social'],
  Block: ['social', 'security'],
  Block2: ['social', 'security'],
  Influencer: ['social', 'business'],
  Viral: ['social'],
  Trending: ['social', 'analytics'],
  TagPerson: ['social'],
  Handshake: ['social', 'business'],
  Handshake2: ['social', 'business'],
  Hand: ['social', 'health'],
  HandMetal: ['social'],
  HandWave: ['social'],
  Fist: ['social'],

  // === FILES & DOCUMENTS ===
  File: ['files'],
  FileText: ['files'],
  FilePlus: ['files'],
  FileMinus: ['files'],
  FileCheck: ['files'],
  FileX: ['files'],
  FileArchive: ['files'],
  FileAudio: ['files', 'media'],
  FileCode: ['files', 'development'],
  FileImage: ['files', 'media'],
  FileVideo: ['files', 'media'],
  Files: ['files'],
  Folder: ['files'],
  FolderPlus: ['files'],
  FolderMinus: ['files'],
  FolderOpen: ['files'],
  Archive: ['files'],
  Archive2: ['files'],
  Clipboard: ['files', 'ui'],
  Clipboard2: ['files', 'ui'],
  ClipboardCheck: ['files', 'ui'],
  ClipboardCheck2: ['files', 'ui'],
  ClipboardList: ['files', 'ui'],
  ClipboardList2: ['files', 'ui'],
  ClipboardCopy: ['files', 'ui'],
  ClipboardCopy2: ['files', 'ui'],
  ClipboardPaste2: ['files', 'ui'],
  ClipboardData: ['files', 'analytics'],
  ClipboardEdit: ['files'],
  ClipboardHeart: ['files', 'health'],
  ClipboardMinus: ['files'],
  ClipboardPlus: ['files'],
  ClipboardSearch: ['files'],
  ClipboardSignature: ['files', 'business'],
  ClipboardText: ['files'],
  ClipboardX2: ['files'],
  Paperclip: ['files', 'communication'],
  Paperclip2: ['files', 'communication'],
  Download: ['files', 'ui'],
  Upload: ['files', 'ui'],
  Save: ['files', 'ui'],
  Save2: ['files', 'ui'],
  SavePlus: ['files', 'ui'],
  Trash: ['files', 'ui'],
  Edit: ['files', 'ui'],
  Binder: ['files', 'education'],
  Template: ['files', 'productivity'],
  Snippet: ['files', 'development'],

  // === DEVICES & HARDWARE ===
  Laptop: ['devices'],
  Monitor: ['devices'],
  Desktop: ['devices'],
  Screen: ['devices'],
  Tablet: ['devices'],
  Smartphone: ['devices'],
  Watch: ['devices'],
  WatchAccessory: ['devices', 'clothing'],
  Printer: ['devices', 'printing'],
  Printer2: ['devices', 'printing'],
  PrinterCheck: ['devices', 'printing'],
  PrinterX: ['devices', 'printing'],
  Mouse: ['devices'],
  Keyboard: ['devices'],
  KeyboardNav: ['devices', 'accessibility'],
  Gamepad: ['devices', 'gaming'],
  Gamepad2: ['devices', 'gaming'],
  Webcam: ['devices'],
  Router: ['devices'],
  UsbDrive: ['devices'],
  SdCard: ['devices'],
  Battery: ['devices'],
  BatteryCharging: ['devices'],
  BatteryLow: ['devices'],
  BatteryEmpty: ['devices'],
  BatteryHalf: ['devices'],
  BatteryQuarter: ['devices'],
  BatteryThreeQuarters: ['devices'],
  Bluetooth: ['devices'],
  Server: ['devices', 'development'],
  Server2: ['devices', 'development'],
  ServerCog: ['devices', 'development'],
  ServerCrash: ['devices', 'development'],
  ServerOff: ['devices', 'development'],
  HardDrive: ['devices', 'development'],
  HardDrive2: ['devices', 'development'],
  Ssd: ['devices', 'development'],
  Cpu: ['devices', 'development'],
  Memory: ['devices', 'development'],
  Ram: ['devices', 'development'],
  Database: ['devices', 'development'],
  Database2: ['devices', 'development'],
  DatabaseBackup: ['devices', 'development'],
  DatabaseZap: ['devices', 'development'],
  Storage: ['devices'],
  Cable: ['devices'],
  Plug2: ['devices'],
  Outlet: ['devices', 'furniture'],
  SurgeProtector: ['devices'],
  Ups: ['devices'],
  Generator: ['devices'],
  Signal: ['devices'],
  SignalHigh: ['devices'],
  SignalLow: ['devices'],
  SignalZero: ['devices'],
  ChipAi: ['devices', 'development'],
  Bot: ['devices', 'development'],
  Robot: ['devices', 'development'],
  Projector: ['devices', 'education'],

  // === TOOLS & UTILITIES ===
  Wrench: ['tools'],
  Hammer: ['tools'],
  Screwdriver: ['tools'],
  Drill: ['tools'],
  Saw: ['tools'],
  Axe: ['tools'],
  Pliers: ['tools'],
  Toolbox: ['tools'],
  Palette: ['tools'],
  Brush: ['tools'],
  Paintbrush: ['tools'],
  Roller: ['tools'],
  Pen: ['tools', 'education'],
  Pen2: ['tools', 'education'],
  PenLine: ['tools'],
  Pencil: ['tools', 'education'],
  Pencil2: ['tools', 'education'],
  PencilLine: ['tools'],
  PenTool: ['tools'],
  Marker: ['tools', 'education'],
  Highlighter: ['tools', 'education'],
  Eraser: ['tools', 'education'],
  Ruler: ['tools', 'education'],
  Ruler2: ['tools', 'education'],
  RulerSquare: ['tools', 'education'],
  Protractor: ['tools', 'education'],
  Caliper: ['tools'],
  TapeMeasure: ['tools'],
  Level: ['tools'],
  Scale2: ['tools'],
  Magnet: ['tools'],
  Flashlight: ['tools'],
  FlashlightOff: ['tools'],
  Torch: ['tools'],
  Lantern: ['tools'],
  Shovel: ['tools', 'nature'],
  Rake: ['tools', 'nature'],
  WateringCan: ['tools', 'nature'],
  GardenHose: ['tools', 'nature'],
  Ladder: ['tools'],
  Glue: ['tools'],
  Tape: ['tools'],
  Scissors2: ['tools'],
  Stapler: ['tools'],
  RubberStamp: ['tools', 'business'],
  Stamp: ['tools', 'business'],
  Stamp2: ['tools', 'business'],
  Wand: ['tools'],
  Wand2: ['tools'],
  WandSparkles: ['tools'],
  Compass: ['tools', 'transportation'],
  Compass2: ['tools'],

  // === DEVELOPMENT & CODE ===
  Code: ['development'],
  Code2: ['development'],
  CodeBlock: ['development'],
  CodeSquare: ['development'],
  Terminal: ['development'],
  Terminal2: ['development'],
  TerminalSquare: ['development'],
  Command: ['development'],
  Api: ['development'],
  Webhook: ['development'],
  Bug: ['development'],
  GitBranch: ['development'],
  GitCommit: ['development'],
  GitFork: ['development'],
  GitMerge: ['development'],
  GitPullRequest: ['development'],
  Branch: ['development'],
  Container: ['development'],
  Function: ['development'],
  Regex: ['development'],
  Html: ['development', 'text'],
  Css: ['development', 'text'],
  JavascriptIcon: ['development', 'brands'],
  TypescriptIcon: ['development', 'brands'],
  Json: ['development'],
  Xml: ['development'],
  Markdown: ['development', 'text'],
  NeuralNetwork: ['development', 'science'],
  BrainCircuit: ['development', 'science'],
  BrainCog: ['development', 'science'],

  // === WEATHER ===
  Cloud: ['weather', 'nature'],
  CloudRain: ['weather', 'nature'],
  CloudSnow: ['weather', 'nature'],
  CloudLightning: ['weather', 'nature'],
  CloudDrizzle: ['weather', 'nature'],
  CloudSun: ['weather', 'nature'],
  CloudFog: ['weather', 'nature'],
  Sun: ['weather', 'nature'],
  Moon: ['weather', 'nature'],
  Sunrise: ['weather', 'nature'],
  Sunset: ['weather', 'nature'],
  Wind: ['weather', 'nature'],
  Thermometer: ['weather', 'health'],
  Thermometer2: ['weather', 'health'],
  ThermometerMedical: ['weather', 'health'],
  Temperature: ['weather'],
  TemperatureDial: ['weather'],
  Barometer: ['weather'],
  Humidity: ['weather'],
  Droplet: ['weather', 'nature'],
  Umbrella: ['weather'],
  Snowflake: ['weather', 'nature'],
  Flame: ['weather', 'nature'],
  Hail: ['weather'],
  Tornado: ['weather', 'nature'],
  Rainbow: ['weather', 'nature'],

  // === CHARTS & DATA VISUALIZATION ===
  Activity: ['charts', 'health'],
  AreaChart: ['charts'],
  BarChart: ['charts'],
  BarChart2: ['charts'],
  BarChartHorizontal: ['charts'],
  LineChart: ['charts'],
  PieChart: ['charts'],
  PieChart2: ['charts'],
  DonutChart: ['charts', 'analytics'],
  Gauge: ['charts'],
  Kanban: ['charts', 'productivity'],
  KanbanBoard: ['charts', 'productivity'],
  Presentation: ['charts', 'education'],
  Presentation2: ['charts', 'education'],
  Table: ['charts', 'ui'],
  Table2: ['charts', 'ui'],
  TrendingDown: ['charts'],
  TrendingUp: ['charts'],
  Statistics: ['charts', 'analytics'],

  // === SECURITY & PRIVACY ===
  Lock: ['security'],
  LockOpen: ['security'],
  LockKeyhole: ['security'],
  Unlock: ['security'],
  Shield: ['security'],
  Shield2: ['security'],
  ShieldCheck: ['security'],
  ShieldOff: ['security'],
  ShieldOff2: ['security'],
  ShieldAlert: ['security'],
  ShieldAlert2: ['security'],
  ShieldPlus: ['security'],
  ShieldPlus2: ['security'],
  ShieldMinus2: ['security'],
  ShieldX: ['security'],
  ShieldLock: ['security'],
  ShieldUnlock: ['security'],
  ShieldUser: ['security'],
  ShieldDollar: ['security', 'finance'],
  Key: ['security'],
  KeyRound: ['security'],
  KeySquare: ['security'],
  Fingerprint: ['security'],
  FaceId: ['security'],
  Scan: ['security', 'ui'],
  Scan2: ['security'],
  ScanFace: ['security'],
  ScanLine: ['security', 'ui'],
  BadgeCheck: ['security', 'social'],
  BadgeCheck2: ['security', 'social'],
  Badge2: ['security'],
  BadgeAlert: ['security'],
  BadgeDollar: ['security', 'finance'],
  BadgeHelp: ['security'],
  BadgeInfo: ['security'],
  BadgeMinus: ['security'],
  BadgePlus: ['security'],
  BadgeX: ['security'],
  BadgePercent: ['security', 'shopping'],
  PercentBadge: ['security', 'shopping'],
  TwoFactor: ['security'],
  Firewall: ['security', 'development'],
  Armor: ['security', 'gaming'],
  Defend: ['security', 'gaming'],
  Guard: ['security'],
  Protection: ['security'],
  Fortress: ['security', 'buildings'],
  Vault: ['security', 'finance'],

  // === SHOPPING & E-COMMERCE ===
  ShoppingCart: ['shopping'],
  ShoppingBag: ['shopping'],
  ShoppingBagPlus: ['shopping'],
  CartCheck: ['shopping'],
  CartMinus: ['shopping'],
  CartPlus: ['shopping'],
  CartX: ['shopping'],
  Basket: ['shopping'],
  CreditCard: ['shopping', 'finance'],
  DollarSign: ['shopping', 'finance'],
  Percent: ['shopping'],
  Percentage: ['shopping'],
  Receipt: ['shopping'],
  Receipt2: ['shopping'],
  ReceiptCheck: ['shopping'],
  ReceiptX: ['shopping'],
  Invoice: ['shopping', 'business'],
  Wallet: ['shopping', 'finance'],
  WalletCards: ['shopping', 'finance'],
  Package: ['shopping', 'files'],
  Truck: ['shopping', 'transportation'],
  Shipping: ['shopping', 'transportation'],
  ShippingFast: ['shopping', 'transportation'],
  FreeShipping: ['shopping'],
  Store: ['shopping', 'buildings'],
  StoreFront: ['shopping', 'buildings'],
  Barcode: ['shopping'],
  Barcode2: ['shopping'],
  QrCode: ['shopping'],
  QrScan: ['shopping'],
  PriceTag: ['shopping'],
  PriceTagPlus: ['shopping'],
  Coupon: ['shopping'],
  Discount: ['shopping'],
  Compare: ['shopping'],
  InStock: ['shopping'],
  OutOfStock: ['shopping'],
  Inventory: ['shopping', 'business'],
  Pickup: ['shopping'],
  Refund: ['shopping', 'finance'],
  Return: ['shopping'],
  Reorder: ['shopping'],
  Wishlist: ['shopping', 'social'],

  // === FINANCE & BANKING ===
  Bank: ['finance', 'buildings'],
  Banknote: ['finance'],
  Bitcoin: ['finance', 'brands'],
  Coin: ['finance', 'gaming'],
  Coins: ['finance'],
  PiggyBank: ['finance'],
  Dividend: ['finance', 'business'],
  Investment2: ['finance', 'business'],
  Profit: ['finance', 'business'],
  Loss: ['finance', 'business'],
  Revenue: ['finance', 'business'],
  Roi: ['finance', 'business'],

  // === HEALTH & MEDICAL ===
  Stethoscope: ['health'],
  Stethoscope2: ['health'],
  Pill: ['health'],
  Pill2: ['health'],
  Pills: ['health'],
  Capsule: ['health'],
  Syringe: ['health'],
  Syringe2: ['health'],
  Vaccine: ['health'],
  Bandage: ['health'],
  Bandage2: ['health'],
  FirstAid: ['health'],
  MedicalBag: ['health'],
  MedicalCross: ['health'],
  Microscope: ['health', 'science'],
  Microscope2: ['health', 'science'],
  TestTube: ['health', 'science'],
  TestTube2: ['health', 'science'],
  TestTubes: ['health', 'science'],
  PetriDish: ['health', 'science'],
  Beaker2: ['health', 'science'],
  Flask2: ['health', 'science'],
  FlaskRound: ['health', 'science'],
  LabResults: ['health'],
  Dna: ['health', 'science'],
  Dna2: ['health', 'science'],
  DnaHelix: ['health', 'science'],
  Bone: ['health'],
  Brain: ['health', 'science'],
  Lungs: ['health'],
  Ear: ['health'],
  EarHearing: ['health', 'accessibility'],
  EarOff: ['health'],
  Footprints: ['health'],
  Wheelchair: ['health', 'accessibility'],
  Wheelchair2: ['health', 'accessibility'],
  Walker: ['health', 'accessibility'],
  Crutches: ['health'],
  Accessibility: ['health', 'accessibility'],
  Hospital: ['health', 'buildings'],
  Ambulance: ['health', 'transportation'],
  Ambulance2: ['health', 'transportation'],
  FireTruck: ['health', 'transportation'],
  Emergency: ['health'],
  Heartbeat: ['health'],
  Pulse: ['health'],
  Vitals: ['health'],
  BloodDrop: ['health'],
  BloodPressure: ['health'],
  BodyScan: ['health'],
  Xray: ['health'],
  Prescription: ['health'],
  Virus: ['health', 'science'],
  Bacteria: ['health', 'science'],
  Immunity: ['health'],
  Oxygen: ['health'],
  Recovery: ['health'],
  Cross: ['health'],
  BriefcaseMedical: ['health', 'business'],
  Dumbbell: ['health', 'sports'],
  Weight: ['health', 'sports'],
  Running: ['health', 'sports'],
  Cycling: ['health', 'sports'],
  Swimming: ['health', 'sports'],

  // === EDUCATION & LEARNING ===
  GraduationCap: ['education'],
  Book: ['education'],
  BookOpen: ['education'],
  BookMarked: ['education'],
  BookClosed: ['education'],
  Library: ['education', 'buildings'],
  Library2: ['education', 'buildings'],
  Bookshelf: ['education', 'furniture'],
  Notebook: ['education'],
  Notebook2: ['education'],
  NotebookPen: ['education'],
  NotebookPen2: ['education'],
  Textbook: ['education'],
  Dictionary: ['education'],
  Calculator: ['education', 'tools'],
  Backpack: ['education'],
  Backpack2: ['education'],
  Lamp: ['education', 'furniture'],
  LampDesk: ['education', 'furniture'],
  LampCeiling: ['furniture'],
  LampFloor: ['furniture'],
  LampWall: ['furniture'],
  Glasses: ['education', 'clothing'],
  Sunglasses: ['clothing'],
  School: ['education', 'buildings'],
  University: ['education', 'buildings'],
  Classroom: ['education', 'buildings'],
  Chalkboard: ['education'],
  Whiteboard: ['education'],
  Certificate: ['education', 'business'],
  Certificate2: ['education', 'business'],
  Diploma: ['education'],
  Assignment: ['education', 'productivity'],
  Homework: ['education'],
  Exam: ['education'],
  Quiz: ['education'],
  Grade: ['education'],
  Attendance: ['education'],
  Course: ['education'],
  Curriculum: ['education'],
  Lecture: ['education'],
  Seminar: ['education'],
  Tutor: ['education'],
  StudentId: ['education'],
  Medal2: ['education', 'sports'],
  Trophy2: ['education', 'sports'],
  Desk2: ['education', 'furniture'],
  Schedule2: ['education', 'productivity'],

  // === BUILDINGS & PLACES ===
  Home: ['buildings', 'ui'],
  House2: ['buildings'],
  HouseCheck: ['buildings'],
  HouseCog: ['buildings'],
  HouseHeart: ['buildings'],
  HousePlus: ['buildings'],
  HouseX: ['buildings'],
  Building: ['buildings'],
  Building2: ['buildings'],
  Apartment: ['buildings'],
  Office: ['buildings', 'business'],
  Factory: ['buildings'],
  Warehouse: ['buildings'],
  Garage: ['buildings'],
  Landmark: ['buildings'],
  Castle: ['buildings'],
  Church: ['buildings'],
  Tower: ['buildings'],
  Lighthouse: ['buildings', 'travel'],
  Tent: ['buildings', 'travel'],
  Hotel: ['buildings', 'travel'],
  HotelBed: ['buildings', 'travel'],
  HotelKey: ['buildings', 'travel'],
  Mountain: ['buildings', 'nature'],
  MountainSnow: ['buildings', 'nature'],
  Fence: ['buildings'],
  Gate: ['buildings'],
  Door: ['buildings'],
  DoorClosed: ['buildings'],
  DoorOpen: ['buildings'],
  Chimney: ['buildings'],

  // === FURNITURE & HOME ===
  Bed: ['furniture'],
  Chair: ['furniture'],
  Desk: ['furniture'],
  Sofa: ['furniture'],
  Bathtub: ['furniture'],
  Sink: ['furniture'],
  Toilet: ['furniture'],
  Faucet: ['furniture'],
  Refrigerator: ['furniture'],
  Microwave: ['furniture'],
  Toaster: ['furniture'],
  Kettle: ['furniture'],
  Blender: ['furniture'],
  Carpet: ['furniture'],
  Curtain: ['furniture'],
  PictureFrame: ['furniture'],
  Candle: ['furniture'],
  Neon: ['furniture'],

  // === CLOTHING & FASHION ===
  Shirt: ['clothing'],
  Tshirt: ['clothing'],
  Hoodie: ['clothing'],
  Sweater: ['clothing'],
  Jacket: ['clothing'],
  Coat: ['clothing'],
  Dress: ['clothing'],
  Pants: ['clothing'],
  Shorts: ['clothing'],
  Hat: ['clothing'],
  Cap: ['clothing'],
  Tie: ['clothing'],
  NameBadge: ['clothing', 'business'],
  IdCard: ['clothing', 'business'],
  BusinessCard: ['clothing', 'business'],

  // === SPORTS & GAMES ===
  Trophy: ['sports'],
  Medal: ['sports'],
  Target: ['sports', 'ui'],
  Target2: ['sports', 'business'],
  Crosshair: ['sports', 'ui'],
  Crosshair2: ['sports', 'ui'],
  Dice1: ['sports', 'gaming'],
  Dice2: ['sports', 'gaming'],
  Dice3: ['sports', 'gaming'],
  Dice4: ['sports', 'gaming'],
  Dice5: ['sports', 'gaming'],
  Dice6: ['sports', 'gaming'],
  Puzzle: ['sports', 'gaming'],
  PuzzlePiece: ['sports', 'gaming'],
  Joystick: ['sports', 'gaming'],
  Joystick2: ['sports', 'gaming'],
  Swords: ['sports', 'gaming'],
  Sword: ['sports', 'gaming'],
  Baseball: ['sports'],
  Basketball: ['sports'],
  Football: ['sports'],
  Soccer: ['sports'],
  Tennis: ['sports'],
  Golf: ['sports'],
  Hockey: ['sports'],
  Volleyball: ['sports'],
  Bowling: ['sports'],
  Skiing: ['sports', 'travel'],
  Hiking: ['sports', 'travel'],
  Bicycle: ['sports', 'transportation'],
  Bike: ['sports', 'transportation'],

  // === GAMING ===
  Console: ['gaming', 'devices'],
  Controller: ['gaming', 'devices'],
  ControllerWireless: ['gaming', 'devices'],
  Handheld: ['gaming', 'devices'],
  Dpad: ['gaming'],
  ButtonA: ['gaming'],
  ButtonB: ['gaming'],
  ButtonX: ['gaming'],
  ButtonY: ['gaming'],
  Trigger: ['gaming'],
  Achievement: ['gaming'],
  HighScore: ['gaming'],
  Leaderboard: ['gaming', 'analytics'],
  LevelUp: ['gaming'],
  XpBar: ['gaming'],
  HealthBar: ['gaming'],
  ManaBar: ['gaming'],
  PowerUp: ['gaming'],
  Loot: ['gaming'],
  Quest: ['gaming'],
  Boss: ['gaming'],
  Multiplayer: ['gaming'],
  Coop: ['gaming'],
  Pvp: ['gaming'],
  Respawn: ['gaming'],
  Crafting: ['gaming'],
  Inventory2: ['gaming'],
  Potion: ['gaming'],
  Arcade: ['gaming', 'buildings'],

  // === FOOD & DRINK ===
  Coffee: ['food'],
  Cup: ['food'],
  Wine: ['food'],
  Beer: ['food'],
  Martini: ['food'],
  Pizza: ['food'],
  Burger: ['food'],
  Hotdog: ['food'],
  Sandwich: ['food'],
  Taco: ['food'],
  Sushi: ['food'],
  Noodles: ['food'],
  Rice: ['food'],
  Soup: ['food'],
  Salad: ['food'],
  Steak: ['food'],
  Chicken: ['food'],
  Bacon: ['food'],
  Egg2: ['food'],
  Bread: ['food'],
  Croissant: ['food'],
  Apple: ['food', 'health', 'brands'],
  Cherry: ['food'],
  Grape: ['food'],
  Banana: ['food'],
  Carrot: ['food', 'health'],
  Shrimp: ['food'],
  Utensils: ['food'],
  UtensilsCrossed: ['food'],
  Fork: ['food'],
  Spoon2: ['food'],
  Knife2: ['food'],
  Chopsticks: ['food'],
  Spatula: ['food'],
  Whisk: ['food'],
  Ladle: ['food'],
  Pan: ['food'],
  Pot: ['food'],
  Plate: ['food'],
  ChefHat: ['food'],
  Cookie: ['food'],
  Cake: ['food'],
  Cupcake: ['food'],
  Donut: ['food'],
  IceCream: ['food'],
  IceCream2: ['food'],
  Lollipop: ['food'],
  Popsicle: ['food'],
  Candy: ['food'],
  Chocolate: ['food'],

  // === TRANSPORTATION ===
  Car: ['transportation'],
  CarFront: ['transportation'],
  Bus: ['transportation'],
  Train: ['transportation'],
  Plane: ['transportation'],
  PlaneTakeoff: ['transportation'],
  PlaneLanding: ['transportation'],
  Helicopter: ['transportation'],
  Ship: ['transportation'],
  Boat: ['transportation'],
  Sailboat: ['transportation'],
  Cruise: ['transportation', 'travel'],
  Rocket: ['transportation'],
  Motorcycle: ['transportation'],
  Scooter: ['transportation'],
  PoliceCar: ['transportation'],
  Fuel: ['transportation'],
  Parking: ['transportation'],
  TrafficCone: ['transportation'],
  Milestone: ['transportation'],
  Milestone2: ['transportation', 'business'],
  Signpost: ['transportation'],
  Map: ['transportation', 'ui'],
  MapPin: ['transportation', 'ui'],
  MapPinned: ['transportation'],
  Globe: ['transportation', 'communication'],
  Globe2: ['transportation'],
  Anchor: ['transportation'],
  Anchor2: ['transportation'],
  Luggage: ['transportation', 'travel'],

  // === TRAVEL & TOURISM ===
  Airport: ['travel', 'transportation'],
  Runway: ['travel', 'transportation'],
  TerminalGate: ['travel', 'transportation'],
  BoardingPass: ['travel'],
  FlightTicket: ['travel'],
  Passport: ['travel'],
  Passport2: ['travel'],
  Visa: ['travel'],
  Baggage: ['travel'],
  BaggageClaim: ['travel'],
  CarryOn: ['travel'],
  CheckIn: ['travel'],
  CheckOut: ['travel'],
  CustomsIcon: ['travel'],
  Immigration: ['travel'],
  Concierge: ['travel'],
  RoomService: ['travel'],
  Reservation: ['travel', 'productivity'],
  Beach: ['travel', 'nature'],
  Pool: ['travel'],
  Spa: ['travel', 'health'],
  Camping: ['travel', 'nature'],
  Safari: ['travel', 'nature', 'brands', 'devices'],
  RoadTrip: ['travel'],
  Ticket: ['travel', 'media'],

  // === NATURE & ENVIRONMENT ===
  Leaf: ['nature'],
  Leaf2: ['nature'],
  Tree: ['nature'],
  Tree2: ['nature'],
  TreePalm: ['nature'],
  TreePine: ['nature'],
  PineTree: ['nature'],
  Flower: ['nature'],
  Flower2: ['nature'],
  Rose: ['nature'],
  Tulip: ['nature'],
  Seedling: ['nature'],
  Sprout: ['nature'],
  Plant2: ['nature'],
  Cactus: ['nature'],
  Palm: ['nature'],
  Fern: ['nature'],
  Ivy: ['nature'],
  Moss: ['nature'],
  Acorn: ['nature'],
  Pinecone: ['nature'],
  Mushroom: ['nature'],
  Waves: ['nature'],
  Ocean: ['nature'],
  River: ['nature'],
  Lake: ['nature'],
  Waterfall: ['nature'],
  Geyser: ['nature'],
  Volcano: ['nature'],
  Desert: ['nature'],
  Island: ['nature'],
  Forest: ['nature'],
  Jungle: ['nature'],
  Cave: ['nature'],
  Boulder: ['nature'],
  Pebbles: ['nature'],
  Crystal: ['nature'],
  Coral: ['nature'],
  Seaweed: ['nature'],
  Shell: ['nature'],
  Starfish: ['nature', 'animals'],
  Fossil: ['nature', 'science'],

  // === ANIMALS ===
  Cat: ['animals'],
  Dog: ['animals'],
  Bird: ['animals'],
  Fish: ['animals'],
  Rabbit: ['animals'],
  Bear: ['animals'],
  Deer: ['animals'],
  Fox: ['animals'],
  Wolf: ['animals'],
  Lion: ['animals'],
  Elephant: ['animals'],
  Horse: ['animals'],
  Turtle: ['animals'],
  Butterfly: ['animals'],
  Bee: ['animals'],
  Ufo: ['animals'],

  // === SHAPES ===
  Circle: ['shapes', 'ui'],
  Square: ['shapes', 'ui'],
  Triangle: ['shapes', 'ui'],
  Rectangle: ['shapes'],
  Oval: ['shapes'],
  Diamond: ['shapes'],
  Hexagon: ['shapes'],
  Octagon: ['shapes'],
  Pentagon: ['shapes'],
  Parallelogram: ['shapes'],
  Trapezoid: ['shapes'],

  // === TEXT & TYPOGRAPHY ===
  Text: ['text'],
  TextCursor: ['text'],
  TextSize: ['text'],
  Bold: ['text'],
  Italic: ['text'],
  Underline: ['text'],
  Strikethrough: ['text'],
  Heading1: ['text'],
  Heading2: ['text'],
  Heading3: ['text'],
  Subscript: ['text'],
  Superscript: ['text'],
  Quote: ['text'],
  Indent: ['text'],
  Outdent: ['text'],

  // === SCIENCE & LABORATORY ===
  Atom2: ['science'],
  Electron: ['science'],
  Nucleus: ['science'],
  Molecule: ['science'],
  Radiation: ['science'],
  Biohazard2: ['science'],
  Experiment: ['science', 'analytics'],
  Hypothesis: ['science', 'analytics'],

  // === MATH & SYMBOLS ===
  Equals: ['shapes'],
  NotEqual: ['shapes'],
  GreaterThan: ['shapes'],
  LessThan: ['shapes'],
  Divide2: ['shapes'],
  Multiply: ['shapes'],
  Fraction: ['shapes'],
  Pi: ['shapes', 'science'],
  Sigma: ['shapes', 'science'],
  Sqrt: ['shapes', 'science'],
  Infinity: ['shapes'],

  // === ACCESSIBILITY ===
  ReducedMotion: ['accessibility'],
  ScreenReader: ['accessibility'],
  SignLanguage: ['accessibility'],
  Braille: ['accessibility'],
  VoiceControl: ['accessibility'],

  // === PRINTING ===
  Copier: ['printing'],
  DocumentPrinter: ['printing'],
  Fax: ['printing', 'communication'],
  Ink: ['printing'],
  Toner: ['printing'],
  PageSetup: ['printing'],
  PaperFeed: ['printing'],
  PrintPreview: ['printing'],
  PrintQueue: ['printing'],
  Scanner: ['printing'],
  Scanner2: ['printing'],

  // === BUSINESS & CORPORATE ===
  Briefcase2: ['business'],
  Portfolio: ['business', 'finance'],
  Contract: ['business'],
  Contract2: ['business'],
  Deal: ['business'],
  Pitch: ['business'],
  Strategy: ['business'],
  Roadmap: ['business', 'productivity'],
  Kpi: ['business', 'analytics'],
  Growth: ['business', 'analytics'],
  Market: ['business'],
  Startup: ['business'],
  Partnership: ['business'],
  Shareholder: ['business', 'finance'],
  Stakeholder: ['business'],
  Competitive: ['business'],
  Feedback: ['business', 'social'],
  Testimonial: ['business', 'social'],
  Review2: ['business', 'social'],
  Rating: ['business', 'social'],
  Survey: ['business', 'analytics'],
  Research: ['business', 'science'],
  Sign: ['business'],

  // === PRODUCTIVITY & TASK MANAGEMENT ===
  Task: ['productivity'],
  TaskCheck: ['productivity'],
  TaskList: ['productivity'],
  Subtask: ['productivity'],
  Assigned: ['productivity'],
  Delegated: ['productivity'],
  Backlog: ['productivity'],
  Sprint: ['productivity'],
  Blocker: ['productivity'],
  Dependency: ['productivity'],
  Deadline: ['productivity'],
  DueDate: ['productivity'],
  Estimate: ['productivity'],
  Priority: ['productivity'],
  PriorityHigh: ['productivity'],
  PriorityLow: ['productivity'],
  InProgress: ['productivity'],
  OnHold: ['productivity'],
  Overdue: ['productivity'],
  Recurring: ['productivity'],
  Reminder: ['productivity'],
  Schedule: ['productivity'],
  TimeTracking: ['productivity'],
  Pomodoro: ['productivity'],
  Focus: ['productivity'],
  Distraction: ['productivity'],
  Automation: ['productivity', 'development'],
  Workflow: ['productivity'],
  Duplicate: ['productivity'],
  Future: ['productivity'],

  // === ANALYTICS & DATA ===
  AbTest: ['analytics'],
  Aggregate: ['analytics'],
  Attribution: ['analytics'],
  Benchmark: ['analytics', 'business'],
  Churn: ['analytics', 'business'],
  Cohort: ['analytics'],
  Correlation: ['analytics'],
  Dashboard: ['analytics', 'ui'],
  DataPoint: ['analytics'],
  Downtrend: ['analytics'],
  Uptrend: ['analytics'],
  Flat: ['analytics'],
  Forecast: ['analytics', 'business'],
  Funnel: ['analytics'],
  FunnelChart: ['analytics'],
  Heatmap: ['analytics'],
  Metric: ['analytics'],
  Outlier: ['analytics'],
  Regression: ['analytics'],
  Retention: ['analytics', 'business'],
  ScatterPlot: ['analytics'],
  Segment: ['analytics'],
  Sparkline: ['analytics'],
  Treemap: ['analytics'],
  Variance: ['analytics'],
  Widget: ['analytics', 'ui'],

  // === LINKS & REFERENCES ===
  Alias: ['files'],
  Backlink: ['files', 'development'],
  Chain: ['ui'],
  ChainBroken: ['ui'],
  Citation: ['education', 'text'],
  DeepLink: ['development'],
  Hyperlink: ['ui', 'development'],
  InternalLink: ['ui', 'development'],
  Link2Off: ['ui'],
  Permalink: ['development'],
  Reference: ['education', 'files'],
  Shortcut: ['ui'],

  // === MISCELLANEOUS ===
  Odometer: ['transportation'],
  Speedometer: ['transportation'],
  SpeedDial: ['ui'],
  Dial: ['ui'],
  Knob: ['ui'],
  Exposure: ['media'],
  Dimension: ['tools'],
  Analytics: ['analytics', 'business'],

  // === BRANDS - SOCIAL ===
  Github: ['brands', 'development'],
  Twitter: ['brands', 'social'],
  XTwitter: ['brands', 'social'],
  Discord: ['brands', 'social', 'communication'],
  Linkedin: ['brands', 'social', 'business'],
  Instagram: ['brands', 'social'],
  Facebook: ['brands', 'social'],
  Meta: ['brands', 'social'],
  Reddit: ['brands', 'social'],
  Tiktok: ['brands', 'social', 'media'],
  Pinterest: ['brands', 'social'],
  Snapchat: ['brands', 'social', 'communication'],
  Threads: ['brands', 'social'],
  Mastodon: ['brands', 'social'],
  Bluesky: ['brands', 'social'],
  Tumblr: ['brands', 'social'],
  Medium: ['brands', 'social', 'text'],
  Strava: ['brands', 'social', 'sports'],
  Goodreads: ['brands', 'social', 'education'],
  Letterboxd: ['brands', 'social', 'media'],
  Substack: ['brands', 'social', 'text'],

  // === BRANDS - AUDIO/VIDEO ===
  Youtube: ['brands', 'media'],
  Spotify: ['brands', 'media'],
  Netflix: ['brands', 'media'],
  Twitch: ['brands', 'media', 'gaming'],
  Soundcloud: ['brands', 'media'],
  Vimeo: ['brands', 'media'],
  Bandcamp: ['brands', 'media'],
  Deezer: ['brands', 'media'],

  // === BRANDS - MESSAGING ===
  Slack: ['brands', 'communication', 'business'],
  Whatsapp: ['brands', 'communication'],
  Telegram: ['brands', 'communication'],
  Messenger: ['brands', 'communication'],
  Wechat: ['brands', 'communication'],
  Line: ['brands', 'communication'],
  Viber: ['brands', 'communication'],
  Teams: ['brands', 'communication', 'business'],
  Zoom: ['brands', 'communication', 'business'],
  Clubhouse: ['brands', 'communication', 'social'],
  SignalApp: ['brands', 'communication', 'security'],

  // === BRANDS - DESIGN ===
  Figma: ['brands', 'tools'],
  Dribbble: ['brands', 'social'],
  Behance: ['brands', 'social'],

  // === BRANDS - BROWSERS ===
  Chrome: ['brands', 'devices'],
  Firefox: ['brands', 'devices'],
  // Safari is mapped above in travel section with brands
  Edge: ['brands', 'devices'],
  Opera: ['brands', 'devices'],

  // === BRANDS - DEVELOPER ===
  Vscode: ['brands', 'development'],
  Npm: ['brands', 'development'],
  Nodejs: ['brands', 'development'],
  ReactLogo: ['brands', 'development'],
  Vue: ['brands', 'development'],
  Angular: ['brands', 'development'],
  Svelte: ['brands', 'development'],
  Nextjs: ['brands', 'development'],
  Tailwind: ['brands', 'development'],
  Vercel: ['brands', 'development'],
  GitLab: ['brands', 'development'],
  Bitbucket: ['brands', 'development'],
  StackOverflow: ['brands', 'development'],
  CodePen: ['brands', 'development'],
  CodeSandbox: ['brands', 'development'],

  // === BRANDS - PRODUCTIVITY ===
  Notion: ['brands', 'productivity'],
  Trello: ['brands', 'productivity'],
  Linear: ['brands', 'productivity'],
  Asana: ['brands', 'productivity'],
  Monday: ['brands', 'productivity'],

  // === BRANDS - CLOUD ===
  Aws: ['brands', 'development'],
  GoogleCloud: ['brands', 'development'],
  Azure: ['brands', 'development'],

  // === BRANDS - PAYMENTS ===
  Stripe: ['brands', 'finance', 'shopping'],
  Paypal: ['brands', 'finance', 'shopping'],

  // === BRANDS - MARKETPLACE ===
  Shopify: ['brands', 'shopping'],
  Etsy: ['brands', 'shopping'],
  Amazon: ['brands', 'shopping'],
  Ebay: ['brands', 'shopping'],
  Airbnb: ['brands', 'travel'],

  // === BRANDS - CREATOR ===
  Patreon: ['brands', 'finance'],
  KoFi: ['brands', 'finance'],

  // === BRANDS - OTHER ===
  // Apple already exists above in food category, but we need the brand version
}

/**
 * Get categories for an icon
 */
export function getIconCategories(iconName: string): IconCategory[] {
  return iconCategories[iconName] || []
}

/**
 * Get all icons in a category
 */
export function getIconsByCategory(category: IconCategory): string[] {
  return Object.entries(iconCategories)
    .filter(([, categories]) => categories.includes(category))
    .map(([name]) => name)
}

/**
 * Check if an icon belongs to a category
 */
export function iconInCategory(iconName: string, category: IconCategory): boolean {
  return iconCategories[iconName]?.includes(category) || false
}

/**
 * Get all unique categories used in the mapping
 */
export function getUsedCategories(): IconCategory[] {
  const categories = new Set<IconCategory>()
  Object.values(iconCategories).forEach(cats => {
    cats.forEach(cat => categories.add(cat))
  })
  return Array.from(categories).sort()
}

/**
 * Get count of icons per category
 */
export function getCategoryCounts(): Record<IconCategory, number> {
  const counts = {} as Record<IconCategory, number>
  categoryList.forEach(cat => {
    counts[cat.id] = 0
  })
  Object.values(iconCategories).forEach(cats => {
    cats.forEach(cat => {
      counts[cat] = (counts[cat] || 0) + 1
    })
  })
  return counts
}
