/**
 * Master list of icons to generate for MotionIcon
 *
 * Target: 1200+ icons
 * Current: 350 icons
 * To generate: 850+ icons
 *
 * Each batch can be processed by a separate agent in parallel.
 */

export interface IconSpec {
  name: string
  description: string
  category: string
  suggestedMotion?: string
}

// ============================================================================
// ARROWS & NAVIGATION (Target: 80 icons, ~55 new)
// ============================================================================
export const ARROWS: IconSpec[] = [
  { name: "ArrowUpCircle", description: "Up arrow inside a circle", category: "arrows", suggestedMotion: "bounce" },
  { name: "ArrowDownCircle", description: "Down arrow inside a circle", category: "arrows", suggestedMotion: "bounce" },
  { name: "ArrowLeftCircle", description: "Left arrow inside a circle", category: "arrows", suggestedMotion: "bounce" },
  { name: "ArrowRightCircle", description: "Right arrow inside a circle", category: "arrows", suggestedMotion: "bounce" },
  { name: "ArrowUpSquare", description: "Up arrow inside a rounded square", category: "arrows", suggestedMotion: "bounce" },
  { name: "ArrowDownSquare", description: "Down arrow inside a rounded square", category: "arrows", suggestedMotion: "bounce" },
  { name: "ArrowUpLeft", description: "Diagonal arrow pointing up-left", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowUpRight", description: "Diagonal arrow pointing up-right", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowDownLeft", description: "Diagonal arrow pointing down-left", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowDownRight", description: "Diagonal arrow pointing down-right", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsExpand", description: "Four arrows pointing outward from center", category: "arrows", suggestedMotion: "scale" },
  { name: "ArrowsCollapse", description: "Four arrows pointing inward to center", category: "arrows", suggestedMotion: "scale" },
  { name: "ArrowsHorizontal", description: "Two arrows pointing left and right", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsVertical", description: "Two arrows pointing up and down", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowBounce", description: "Arrow with bounce indicator below", category: "arrows", suggestedMotion: "bounce" },
  { name: "ArrowCurveRight", description: "Curved arrow bending to the right", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowCurveLeft", description: "Curved arrow bending to the left", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowCurveUp", description: "Curved arrow bending upward", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowCurveDown", description: "Curved arrow bending downward", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowUturnLeft", description: "U-turn arrow going left", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowUturnRight", description: "U-turn arrow going right", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowUturnUp", description: "U-turn arrow going up", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowUturnDown", description: "U-turn arrow going down", category: "arrows", suggestedMotion: "draw" },
  { name: "ArrowsSort", description: "Up and down arrows for sorting", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsSortAsc", description: "Arrow indicating ascending sort", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsSortDesc", description: "Arrow indicating descending sort", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsSwapHorizontal", description: "Two arrows swapping horizontally", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsSwapVertical", description: "Two arrows swapping vertically", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsMove", description: "Four-directional move arrows", category: "arrows", suggestedMotion: "translate" },
  { name: "ArrowsResize", description: "Diagonal resize arrows", category: "arrows", suggestedMotion: "scale" },
]

// ============================================================================
// UI ELEMENTS (Target: 120 icons, ~85 new)
// ============================================================================
export const UI: IconSpec[] = [
  { name: "MenuAlt", description: "Alternative hamburger menu with two lines", category: "ui", suggestedMotion: "scale" },
  { name: "MenuDots", description: "Three vertical dots menu (kebab)", category: "ui", suggestedMotion: "scale" },
  { name: "MenuDotsHorizontal", description: "Three horizontal dots menu (meatball)", category: "ui", suggestedMotion: "scale" },
  { name: "MenuGrid", description: "Nine dot grid menu (waffle)", category: "ui", suggestedMotion: "scale" },
  { name: "PlusCircle", description: "Plus sign inside a circle", category: "ui", suggestedMotion: "scale" },
  { name: "PlusSquare", description: "Plus sign inside a square", category: "ui", suggestedMotion: "scale" },
  { name: "MinusCircle", description: "Minus sign inside a circle", category: "ui", suggestedMotion: "scale" },
  { name: "MinusSquare", description: "Minus sign inside a square", category: "ui", suggestedMotion: "scale" },
  { name: "CheckCircle", description: "Checkmark inside a circle", category: "ui", suggestedMotion: "draw" },
  { name: "CheckSquare", description: "Checkmark inside a square", category: "ui", suggestedMotion: "draw" },
  { name: "CheckDouble", description: "Double checkmark (read receipt)", category: "ui", suggestedMotion: "draw" },
  { name: "XCircle", description: "X mark inside a circle", category: "ui", suggestedMotion: "scale" },
  { name: "XSquare", description: "X mark inside a square", category: "ui", suggestedMotion: "scale" },
  { name: "SearchPlus", description: "Magnifying glass with plus", category: "ui", suggestedMotion: "scale" },
  { name: "SearchMinus", description: "Magnifying glass with minus", category: "ui", suggestedMotion: "scale" },
  { name: "FilterAlt", description: "Alternative filter icon (sliders)", category: "ui", suggestedMotion: "scale" },
  { name: "FilterX", description: "Filter with X (clear filter)", category: "ui", suggestedMotion: "scale" },
  { name: "SortAlphaAsc", description: "A-Z sort ascending", category: "ui", suggestedMotion: "translate" },
  { name: "SortAlphaDesc", description: "Z-A sort descending", category: "ui", suggestedMotion: "translate" },
  { name: "SortNumericAsc", description: "1-9 sort ascending", category: "ui", suggestedMotion: "translate" },
  { name: "SortNumericDesc", description: "9-1 sort descending", category: "ui", suggestedMotion: "translate" },
  { name: "GridSmall", description: "Small grid layout (many items)", category: "ui", suggestedMotion: "scale" },
  { name: "GridLarge", description: "Large grid layout (few items)", category: "ui", suggestedMotion: "scale" },
  { name: "ListBullet", description: "Bulleted list", category: "ui", suggestedMotion: "scale" },
  { name: "ListNumbered", description: "Numbered list", category: "ui", suggestedMotion: "scale" },
  { name: "ListCheck", description: "Checklist with checkmarks", category: "ui", suggestedMotion: "scale" },
  { name: "LayoutSidebar", description: "Layout with sidebar", category: "ui", suggestedMotion: "scale" },
  { name: "LayoutSidebarRight", description: "Layout with right sidebar", category: "ui", suggestedMotion: "scale" },
  { name: "LayoutHeader", description: "Layout with header", category: "ui", suggestedMotion: "scale" },
  { name: "LayoutFooter", description: "Layout with footer", category: "ui", suggestedMotion: "scale" },
  { name: "LayoutGrid", description: "Grid layout with multiple panels", category: "ui", suggestedMotion: "scale" },
  { name: "LayoutDashboard", description: "Dashboard layout with widgets", category: "ui", suggestedMotion: "scale" },
  { name: "Maximize", description: "Maximize/fullscreen icon", category: "ui", suggestedMotion: "scale" },
  { name: "Minimize", description: "Minimize icon", category: "ui", suggestedMotion: "scale" },
  { name: "ExternalLink", description: "Arrow pointing out of box (external link)", category: "ui", suggestedMotion: "translate" },
  { name: "InternalLink", description: "Arrow pointing into box (internal link)", category: "ui", suggestedMotion: "translate" },
  { name: "LinkAlt", description: "Chain link alternative", category: "ui", suggestedMotion: "scale" },
  { name: "Unlink", description: "Broken chain link", category: "ui", suggestedMotion: "shake" },
  { name: "CopyAlt", description: "Alternative copy icon", category: "ui", suggestedMotion: "scale" },
  { name: "ClipboardCopy", description: "Clipboard with copy action", category: "ui", suggestedMotion: "scale" },
  { name: "ClipboardPaste", description: "Clipboard with paste action", category: "ui", suggestedMotion: "scale" },
  { name: "ClipboardCheck", description: "Clipboard with checkmark", category: "ui", suggestedMotion: "draw" },
  { name: "ClipboardX", description: "Clipboard with X", category: "ui", suggestedMotion: "scale" },
  { name: "ClipboardList", description: "Clipboard with list", category: "ui", suggestedMotion: "scale" },
  { name: "Cut", description: "Scissors for cut action", category: "ui", suggestedMotion: "scale" },
  { name: "TrashAlt", description: "Alternative trash can", category: "ui", suggestedMotion: "shake" },
  { name: "TrashRestore", description: "Trash with restore arrow", category: "ui", suggestedMotion: "bounce" },
  { name: "ArchiveIn", description: "Archive with down arrow", category: "ui", suggestedMotion: "translate" },
  { name: "ArchiveOut", description: "Archive with up arrow", category: "ui", suggestedMotion: "translate" },
  { name: "DownloadCloud", description: "Cloud with download arrow", category: "ui", suggestedMotion: "bounce" },
  { name: "UploadCloud", description: "Cloud with upload arrow", category: "ui", suggestedMotion: "bounce" },
  { name: "ShareAlt", description: "Alternative share icon (nodes)", category: "ui", suggestedMotion: "scale" },
  { name: "ShareBox", description: "Share from box icon", category: "ui", suggestedMotion: "translate" },
  { name: "RefreshCw", description: "Clockwise refresh arrows", category: "ui", suggestedMotion: "rotate" },
  { name: "RefreshCcw", description: "Counter-clockwise refresh arrows", category: "ui", suggestedMotion: "rotate" },
  { name: "SyncAlt", description: "Alternative sync icon", category: "ui", suggestedMotion: "rotate" },
  { name: "LoaderCircle", description: "Circular loader/spinner", category: "ui", suggestedMotion: "spin" },
  { name: "LoaderDots", description: "Three dot loader", category: "ui", suggestedMotion: "pulse" },
  { name: "MoreHorizontal", description: "Three horizontal dots", category: "ui", suggestedMotion: "scale" },
  { name: "MoreVertical", description: "Three vertical dots", category: "ui", suggestedMotion: "scale" },
  { name: "GripHorizontal", description: "Horizontal drag handle", category: "ui", suggestedMotion: "scale" },
  { name: "GripVertical", description: "Vertical drag handle", category: "ui", suggestedMotion: "scale" },
  { name: "Drag", description: "Drag indicator (six dots)", category: "ui", suggestedMotion: "scale" },
  { name: "DragHandle", description: "Horizontal lines drag handle", category: "ui", suggestedMotion: "scale" },
  { name: "Slider", description: "Horizontal slider", category: "ui", suggestedMotion: "translate" },
  { name: "SliderVertical", description: "Vertical slider", category: "ui", suggestedMotion: "translate" },
  { name: "Toggle", description: "Toggle switch", category: "ui", suggestedMotion: "translate" },
  { name: "ToggleLeft", description: "Toggle switch (off/left)", category: "ui", suggestedMotion: "translate" },
  { name: "ToggleRight", description: "Toggle switch (on/right)", category: "ui", suggestedMotion: "translate" },
  { name: "Radio", description: "Radio button (unselected)", category: "ui", suggestedMotion: "scale" },
  { name: "RadioSelected", description: "Radio button (selected)", category: "ui", suggestedMotion: "scale" },
  { name: "Checkbox", description: "Checkbox (unchecked)", category: "ui", suggestedMotion: "scale" },
  { name: "CheckboxChecked", description: "Checkbox (checked)", category: "ui", suggestedMotion: "draw" },
  { name: "Dropdown", description: "Dropdown selector", category: "ui", suggestedMotion: "scale" },
  { name: "Select", description: "Select/combobox icon", category: "ui", suggestedMotion: "scale" },
  { name: "InputCursor", description: "Text input cursor", category: "ui", suggestedMotion: "pulse" },
  { name: "InputText", description: "Text input field", category: "ui", suggestedMotion: "scale" },
  { name: "InputSearch", description: "Search input field", category: "ui", suggestedMotion: "scale" },
  { name: "InputPassword", description: "Password input with dots", category: "ui", suggestedMotion: "scale" },
  { name: "FormInput", description: "Form text field", category: "ui", suggestedMotion: "scale" },
  { name: "FormTextarea", description: "Form textarea", category: "ui", suggestedMotion: "scale" },
  { name: "Modal", description: "Modal/dialog window", category: "ui", suggestedMotion: "scale" },
  { name: "Popover", description: "Popover/tooltip", category: "ui", suggestedMotion: "scale" },
  { name: "Toast", description: "Toast notification", category: "ui", suggestedMotion: "translate" },
  { name: "Badge", description: "Badge/tag", category: "ui", suggestedMotion: "scale" },
  { name: "BadgeDot", description: "Badge with notification dot", category: "ui", suggestedMotion: "pulse" },
]

// ============================================================================
// DEVELOPER & CODE (Target: 60 icons, ~55 new)
// ============================================================================
export const DEVELOPER: IconSpec[] = [
  { name: "Code", description: "Code brackets < />", category: "developer", suggestedMotion: "scale" },
  { name: "CodeBlock", description: "Code block with multiple lines", category: "developer", suggestedMotion: "scale" },
  { name: "Terminal", description: "Terminal/command line window", category: "developer", suggestedMotion: "scale" },
  { name: "TerminalSquare", description: "Terminal in a square", category: "developer", suggestedMotion: "scale" },
  { name: "Console", description: "Console with prompt", category: "developer", suggestedMotion: "pulse" },
  { name: "GitBranch", description: "Git branch", category: "developer", suggestedMotion: "draw" },
  { name: "GitCommit", description: "Git commit (dot on line)", category: "developer", suggestedMotion: "scale" },
  { name: "GitMerge", description: "Git merge (branches joining)", category: "developer", suggestedMotion: "draw" },
  { name: "GitPullRequest", description: "Git pull request", category: "developer", suggestedMotion: "draw" },
  { name: "GitFork", description: "Git fork (branches splitting)", category: "developer", suggestedMotion: "draw" },
  { name: "GitCompare", description: "Git compare/diff", category: "developer", suggestedMotion: "scale" },
  { name: "Bug", description: "Bug/insect icon", category: "developer", suggestedMotion: "shake" },
  { name: "BugOff", description: "Bug with X (fixed)", category: "developer", suggestedMotion: "scale" },
  { name: "Debug", description: "Debug (bug with magnifier)", category: "developer", suggestedMotion: "scale" },
  { name: "Api", description: "API connection icon", category: "developer", suggestedMotion: "pulse" },
  { name: "Webhook", description: "Webhook hook icon", category: "developer", suggestedMotion: "scale" },
  { name: "Function", description: "Function f(x) icon", category: "developer", suggestedMotion: "scale" },
  { name: "Variable", description: "Variable (x) icon", category: "developer", suggestedMotion: "scale" },
  { name: "Constant", description: "Constant icon", category: "developer", suggestedMotion: "scale" },
  { name: "Array", description: "Array brackets [ ]", category: "developer", suggestedMotion: "scale" },
  { name: "Object", description: "Object/JSON braces { }", category: "developer", suggestedMotion: "scale" },
  { name: "Regex", description: "Regular expression icon", category: "developer", suggestedMotion: "scale" },
  { name: "Binary", description: "Binary 01 icon", category: "developer", suggestedMotion: "scale" },
  { name: "Hex", description: "Hexadecimal icon", category: "developer", suggestedMotion: "scale" },
  { name: "Package", description: "Package/module box", category: "developer", suggestedMotion: "scale" },
  { name: "PackageOpen", description: "Open package box", category: "developer", suggestedMotion: "scale" },
  { name: "PackageCheck", description: "Package with checkmark", category: "developer", suggestedMotion: "draw" },
  { name: "PackagePlus", description: "Package with plus (add)", category: "developer", suggestedMotion: "scale" },
  { name: "PackageMinus", description: "Package with minus (remove)", category: "developer", suggestedMotion: "scale" },
  { name: "Deploy", description: "Deploy/rocket launch", category: "developer", suggestedMotion: "bounce" },
  { name: "Rollback", description: "Rollback arrow", category: "developer", suggestedMotion: "rotate" },
  { name: "Container", description: "Container/Docker icon", category: "developer", suggestedMotion: "scale" },
  { name: "Kubernetes", description: "Kubernetes wheel", category: "developer", suggestedMotion: "rotate" },
  { name: "CloudServer", description: "Cloud with server", category: "developer", suggestedMotion: "scale" },
  { name: "ServerRack", description: "Server rack", category: "developer", suggestedMotion: "scale" },
  { name: "ServerCog", description: "Server with cog", category: "developer", suggestedMotion: "rotate" },
  { name: "Database", description: "Database cylinder", category: "developer", suggestedMotion: "scale" },
  { name: "DatabasePlus", description: "Database with plus", category: "developer", suggestedMotion: "scale" },
  { name: "DatabaseMinus", description: "Database with minus", category: "developer", suggestedMotion: "scale" },
  { name: "DatabaseCog", description: "Database with settings cog", category: "developer", suggestedMotion: "rotate" },
  { name: "Table", description: "Data table grid", category: "developer", suggestedMotion: "scale" },
  { name: "TableCells", description: "Table with cells", category: "developer", suggestedMotion: "scale" },
  { name: "Schema", description: "Database schema", category: "developer", suggestedMotion: "scale" },
  { name: "Query", description: "Query/search in database", category: "developer", suggestedMotion: "scale" },
  { name: "Logs", description: "Log lines", category: "developer", suggestedMotion: "scale" },
  { name: "LogIn", description: "Log in arrow", category: "developer", suggestedMotion: "translate" },
  { name: "LogOut", description: "Log out arrow", category: "developer", suggestedMotion: "translate" },
  { name: "Test", description: "Test tube / testing", category: "developer", suggestedMotion: "scale" },
  { name: "TestPassed", description: "Test with checkmark", category: "developer", suggestedMotion: "draw" },
  { name: "TestFailed", description: "Test with X", category: "developer", suggestedMotion: "shake" },
  { name: "Ci", description: "CI/CD pipeline", category: "developer", suggestedMotion: "rotate" },
  { name: "Pipeline", description: "Pipeline stages", category: "developer", suggestedMotion: "draw" },
  { name: "Workflow", description: "Workflow nodes", category: "developer", suggestedMotion: "draw" },
  { name: "Npm", description: "npm logo style", category: "developer", suggestedMotion: "scale" },
  { name: "Yarn", description: "Yarn package manager style", category: "developer", suggestedMotion: "scale" },
]

// ============================================================================
// AI & MACHINE LEARNING (Target: 30 icons, all new)
// ============================================================================
export const AI: IconSpec[] = [
  { name: "Brain", description: "Brain icon for AI", category: "ai", suggestedMotion: "pulse" },
  { name: "BrainCircuit", description: "Brain with circuit patterns", category: "ai", suggestedMotion: "pulse" },
  { name: "BrainCog", description: "Brain with cog/settings", category: "ai", suggestedMotion: "rotate" },
  { name: "NeuralNetwork", description: "Neural network nodes connected", category: "ai", suggestedMotion: "pulse" },
  { name: "Robot", description: "Robot head/face", category: "ai", suggestedMotion: "scale" },
  { name: "Bot", description: "Chat bot icon", category: "ai", suggestedMotion: "pulse" },
  { name: "ChipAi", description: "AI chip/processor", category: "ai", suggestedMotion: "pulse" },
  { name: "Sparkles", description: "Magic sparkles (AI generation)", category: "ai", suggestedMotion: "pulse" },
  { name: "SparklesAlt", description: "Alternative sparkles", category: "ai", suggestedMotion: "scale" },
  { name: "Wand", description: "Magic wand", category: "ai", suggestedMotion: "shake" },
  { name: "WandSparkles", description: "Magic wand with sparkles", category: "ai", suggestedMotion: "shake" },
  { name: "Stars", description: "Multiple stars (AI magic)", category: "ai", suggestedMotion: "pulse" },
  { name: "Lightbulb", description: "Lightbulb idea", category: "ai", suggestedMotion: "pulse" },
  { name: "LightbulbOff", description: "Lightbulb off", category: "ai", suggestedMotion: "scale" },
  { name: "MessageAi", description: "Chat message with AI sparkle", category: "ai", suggestedMotion: "pulse" },
  { name: "Prompt", description: "AI prompt input", category: "ai", suggestedMotion: "scale" },
  { name: "Generate", description: "Generate/create with AI", category: "ai", suggestedMotion: "rotate" },
  { name: "Transform", description: "Transform/convert", category: "ai", suggestedMotion: "rotate" },
  { name: "Analyze", description: "Analyze/inspect", category: "ai", suggestedMotion: "scale" },
  { name: "Learn", description: "Learning/training", category: "ai", suggestedMotion: "pulse" },
  { name: "Model", description: "AI model cube", category: "ai", suggestedMotion: "rotate" },
  { name: "ModelTraining", description: "Model in training", category: "ai", suggestedMotion: "spin" },
  { name: "Inference", description: "AI inference/prediction", category: "ai", suggestedMotion: "pulse" },
  { name: "ComputerVision", description: "Eye for computer vision", category: "ai", suggestedMotion: "scale" },
  { name: "TextAi", description: "Text with AI indicator", category: "ai", suggestedMotion: "pulse" },
  { name: "AudioAi", description: "Audio wave with AI", category: "ai", suggestedMotion: "pulse" },
  { name: "ImageAi", description: "Image with AI sparkle", category: "ai", suggestedMotion: "pulse" },
  { name: "VideoAi", description: "Video with AI", category: "ai", suggestedMotion: "pulse" },
  { name: "Embedding", description: "Embedding vectors", category: "ai", suggestedMotion: "scale" },
  { name: "Vector", description: "Vector/dimension", category: "ai", suggestedMotion: "scale" },
]

// ============================================================================
// MEDIA & PLAYER (Target: 60 icons, ~40 new)
// ============================================================================
export const MEDIA: IconSpec[] = [
  { name: "PlayCircle", description: "Play button in circle", category: "media", suggestedMotion: "scale" },
  { name: "PlaySquare", description: "Play button in square", category: "media", suggestedMotion: "scale" },
  { name: "PauseCircle", description: "Pause button in circle", category: "media", suggestedMotion: "scale" },
  { name: "PauseSquare", description: "Pause button in square", category: "media", suggestedMotion: "scale" },
  { name: "StopCircle", description: "Stop button in circle", category: "media", suggestedMotion: "scale" },
  { name: "RecordCircle", description: "Record button (red dot)", category: "media", suggestedMotion: "pulse" },
  { name: "FastForward", description: "Fast forward double arrows", category: "media", suggestedMotion: "translate" },
  { name: "Rewind", description: "Rewind double arrows", category: "media", suggestedMotion: "translate" },
  { name: "SkipForward", description: "Skip to next", category: "media", suggestedMotion: "translate" },
  { name: "SkipBack", description: "Skip to previous", category: "media", suggestedMotion: "translate" },
  { name: "Volume", description: "Volume speaker", category: "media", suggestedMotion: "scale" },
  { name: "Volume1", description: "Volume low (one wave)", category: "media", suggestedMotion: "scale" },
  { name: "Volume2", description: "Volume medium (two waves)", category: "media", suggestedMotion: "scale" },
  { name: "VolumeX", description: "Volume muted with X", category: "media", suggestedMotion: "shake" },
  { name: "VolumeOff", description: "Volume off (no waves)", category: "media", suggestedMotion: "scale" },
  { name: "Repeat", description: "Repeat/loop arrows", category: "media", suggestedMotion: "rotate" },
  { name: "Repeat1", description: "Repeat one track", category: "media", suggestedMotion: "rotate" },
  { name: "Shuffle", description: "Shuffle crossed arrows", category: "media", suggestedMotion: "shake" },
  { name: "Playlist", description: "Playlist/queue", category: "media", suggestedMotion: "scale" },
  { name: "PlaylistAdd", description: "Add to playlist", category: "media", suggestedMotion: "scale" },
  { name: "PlaylistRemove", description: "Remove from playlist", category: "media", suggestedMotion: "scale" },
  { name: "Music", description: "Music note", category: "media", suggestedMotion: "bounce" },
  { name: "Music2", description: "Double music notes", category: "media", suggestedMotion: "bounce" },
  { name: "Music3", description: "Triple music notes", category: "media", suggestedMotion: "bounce" },
  { name: "Music4", description: "Music notes with staff", category: "media", suggestedMotion: "bounce" },
  { name: "Mic", description: "Microphone", category: "media", suggestedMotion: "scale" },
  { name: "MicOff", description: "Microphone with slash", category: "media", suggestedMotion: "shake" },
  { name: "Mic2", description: "Podcast/studio microphone", category: "media", suggestedMotion: "scale" },
  { name: "Headphones", description: "Headphones", category: "media", suggestedMotion: "scale" },
  { name: "HeadphonesOff", description: "Headphones with slash", category: "media", suggestedMotion: "shake" },
  { name: "Speaker", description: "Speaker/audio output", category: "media", suggestedMotion: "pulse" },
  { name: "Radio", description: "Radio with antenna", category: "media", suggestedMotion: "pulse" },
  { name: "Podcast", description: "Podcast icon", category: "media", suggestedMotion: "pulse" },
  { name: "Video", description: "Video camera", category: "media", suggestedMotion: "scale" },
  { name: "VideoOff", description: "Video camera with slash", category: "media", suggestedMotion: "shake" },
  { name: "Camera", description: "Photo camera", category: "media", suggestedMotion: "scale" },
  { name: "CameraOff", description: "Camera with slash", category: "media", suggestedMotion: "shake" },
  { name: "Image", description: "Image/picture", category: "media", suggestedMotion: "scale" },
  { name: "ImagePlus", description: "Add image", category: "media", suggestedMotion: "scale" },
  { name: "ImageMinus", description: "Remove image", category: "media", suggestedMotion: "scale" },
  { name: "Images", description: "Multiple images/gallery", category: "media", suggestedMotion: "scale" },
  { name: "Film", description: "Film reel", category: "media", suggestedMotion: "rotate" },
  { name: "Clapperboard", description: "Movie clapperboard", category: "media", suggestedMotion: "scale" },
  { name: "Tv", description: "Television", category: "media", suggestedMotion: "scale" },
  { name: "Tv2", description: "Modern flat TV", category: "media", suggestedMotion: "scale" },
  { name: "Monitor", description: "Computer monitor", category: "media", suggestedMotion: "scale" },
  { name: "MonitorPlay", description: "Monitor with play button", category: "media", suggestedMotion: "scale" },
  { name: "Cast", description: "Cast/broadcast", category: "media", suggestedMotion: "pulse" },
  { name: "Airplay", description: "Airplay icon", category: "media", suggestedMotion: "scale" },
  { name: "Subtitles", description: "Subtitles/captions", category: "media", suggestedMotion: "scale" },
  { name: "Waveform", description: "Audio waveform", category: "media", suggestedMotion: "pulse" },
  { name: "Equalizer", description: "Audio equalizer bars", category: "media", suggestedMotion: "pulse" },
]

// ============================================================================
// SECURITY (Target: 50 icons, ~35 new)
// ============================================================================
export const SECURITY: IconSpec[] = [
  { name: "Lock", description: "Locked padlock", category: "security", suggestedMotion: "scale" },
  { name: "LockOpen", description: "Unlocked padlock", category: "security", suggestedMotion: "scale" },
  { name: "LockKeyhole", description: "Lock with keyhole", category: "security", suggestedMotion: "scale" },
  { name: "Unlock", description: "Unlock action", category: "security", suggestedMotion: "shake" },
  { name: "Key", description: "Key", category: "security", suggestedMotion: "rotate" },
  { name: "KeyRound", description: "Round/modern key", category: "security", suggestedMotion: "rotate" },
  { name: "KeySquare", description: "Key in square", category: "security", suggestedMotion: "scale" },
  { name: "Shield", description: "Shield", category: "security", suggestedMotion: "scale" },
  { name: "ShieldCheck", description: "Shield with checkmark", category: "security", suggestedMotion: "draw" },
  { name: "ShieldAlert", description: "Shield with alert", category: "security", suggestedMotion: "shake" },
  { name: "ShieldX", description: "Shield with X", category: "security", suggestedMotion: "shake" },
  { name: "ShieldOff", description: "Shield disabled", category: "security", suggestedMotion: "scale" },
  { name: "ShieldPlus", description: "Shield with plus", category: "security", suggestedMotion: "scale" },
  { name: "ShieldQuestion", description: "Shield with question mark", category: "security", suggestedMotion: "scale" },
  { name: "Eye", description: "Eye (visible)", category: "security", suggestedMotion: "scale" },
  { name: "EyeOff", description: "Eye with slash (hidden)", category: "security", suggestedMotion: "scale" },
  { name: "EyeClosed", description: "Closed eye", category: "security", suggestedMotion: "scale" },
  { name: "Fingerprint", description: "Fingerprint", category: "security", suggestedMotion: "draw" },
  { name: "FaceId", description: "Face recognition", category: "security", suggestedMotion: "scale" },
  { name: "Scan", description: "Scan icon", category: "security", suggestedMotion: "pulse" },
  { name: "ScanFace", description: "Face scan", category: "security", suggestedMotion: "pulse" },
  { name: "ScanLine", description: "Scanning line", category: "security", suggestedMotion: "translate" },
  { name: "Password", description: "Password asterisks", category: "security", suggestedMotion: "scale" },
  { name: "TwoFactor", description: "2FA icon", category: "security", suggestedMotion: "scale" },
  { name: "Otp", description: "One-time password", category: "security", suggestedMotion: "scale" },
  { name: "Verified", description: "Verified badge", category: "security", suggestedMotion: "draw" },
  { name: "Unverified", description: "Unverified/unknown", category: "security", suggestedMotion: "scale" },
  { name: "Certificate", description: "Certificate/diploma", category: "security", suggestedMotion: "scale" },
  { name: "Firewall", description: "Firewall icon", category: "security", suggestedMotion: "scale" },
  { name: "Encrypt", description: "Encrypt lock", category: "security", suggestedMotion: "scale" },
  { name: "Decrypt", description: "Decrypt unlock", category: "security", suggestedMotion: "scale" },
  { name: "Https", description: "HTTPS secure lock", category: "security", suggestedMotion: "scale" },
  { name: "PrivacyTip", description: "Privacy shield tip", category: "security", suggestedMotion: "scale" },
  { name: "Incognito", description: "Incognito/private mode", category: "security", suggestedMotion: "scale" },
  { name: "AlertTriangle", description: "Warning triangle", category: "security", suggestedMotion: "shake" },
  { name: "AlertCircle", description: "Warning circle", category: "security", suggestedMotion: "shake" },
  { name: "AlertOctagon", description: "Stop/danger octagon", category: "security", suggestedMotion: "shake" },
  { name: "BugAlt", description: "Security bug", category: "security", suggestedMotion: "shake" },
  { name: "Virus", description: "Computer virus", category: "security", suggestedMotion: "shake" },
  { name: "VirusOff", description: "Virus blocked", category: "security", suggestedMotion: "scale" },
]

// ============================================================================
// FINANCE & COMMERCE (Target: 60 icons, ~40 new)
// ============================================================================
export const FINANCE: IconSpec[] = [
  { name: "CreditCard", description: "Credit card", category: "finance", suggestedMotion: "scale" },
  { name: "CreditCardOff", description: "Credit card declined", category: "finance", suggestedMotion: "shake" },
  { name: "Wallet", description: "Wallet", category: "finance", suggestedMotion: "scale" },
  { name: "WalletCards", description: "Wallet with cards", category: "finance", suggestedMotion: "scale" },
  { name: "Banknote", description: "Paper money", category: "finance", suggestedMotion: "scale" },
  { name: "Coins", description: "Stack of coins", category: "finance", suggestedMotion: "scale" },
  { name: "Coin", description: "Single coin", category: "finance", suggestedMotion: "rotate" },
  { name: "DollarSign", description: "Dollar sign $", category: "finance", suggestedMotion: "scale" },
  { name: "Euro", description: "Euro sign €", category: "finance", suggestedMotion: "scale" },
  { name: "PoundSterling", description: "British pound £", category: "finance", suggestedMotion: "scale" },
  { name: "JapaneseYen", description: "Japanese yen ¥", category: "finance", suggestedMotion: "scale" },
  { name: "IndianRupee", description: "Indian rupee ₹", category: "finance", suggestedMotion: "scale" },
  { name: "Bitcoin", description: "Bitcoin ₿", category: "finance", suggestedMotion: "scale" },
  { name: "Ethereum", description: "Ethereum diamond", category: "finance", suggestedMotion: "scale" },
  { name: "CircleDollarSign", description: "Dollar in circle", category: "finance", suggestedMotion: "scale" },
  { name: "HandCoins", description: "Hand holding coins", category: "finance", suggestedMotion: "bounce" },
  { name: "HandCreditCard", description: "Hand with credit card", category: "finance", suggestedMotion: "scale" },
  { name: "Landmark", description: "Bank building", category: "finance", suggestedMotion: "scale" },
  { name: "Vault", description: "Safe vault", category: "finance", suggestedMotion: "scale" },
  { name: "PiggyBank", description: "Piggy bank", category: "finance", suggestedMotion: "bounce" },
  { name: "Receipt", description: "Receipt/invoice", category: "finance", suggestedMotion: "scale" },
  { name: "ReceiptText", description: "Receipt with text", category: "finance", suggestedMotion: "scale" },
  { name: "Calculator", description: "Calculator", category: "finance", suggestedMotion: "scale" },
  { name: "Percent", description: "Percentage sign", category: "finance", suggestedMotion: "scale" },
  { name: "BadgePercent", description: "Discount badge", category: "finance", suggestedMotion: "scale" },
  { name: "TrendingUp", description: "Trending up arrow", category: "finance", suggestedMotion: "draw" },
  { name: "TrendingDown", description: "Trending down arrow", category: "finance", suggestedMotion: "draw" },
  { name: "LineChart", description: "Line chart/graph", category: "finance", suggestedMotion: "draw" },
  { name: "BarChart", description: "Bar chart", category: "finance", suggestedMotion: "scale" },
  { name: "BarChart2", description: "Bar chart variant", category: "finance", suggestedMotion: "scale" },
  { name: "BarChart3", description: "Horizontal bar chart", category: "finance", suggestedMotion: "scale" },
  { name: "BarChart4", description: "Bar chart with trend", category: "finance", suggestedMotion: "scale" },
  { name: "PieChart", description: "Pie chart", category: "finance", suggestedMotion: "rotate" },
  { name: "Activity", description: "Activity chart", category: "finance", suggestedMotion: "pulse" },
  { name: "ShoppingCart", description: "Shopping cart", category: "finance", suggestedMotion: "scale" },
  { name: "ShoppingBag", description: "Shopping bag", category: "finance", suggestedMotion: "scale" },
  { name: "Store", description: "Store/shop", category: "finance", suggestedMotion: "scale" },
  { name: "Tag", description: "Price tag", category: "finance", suggestedMotion: "scale" },
  { name: "Tags", description: "Multiple tags", category: "finance", suggestedMotion: "scale" },
  { name: "Barcode", description: "Barcode", category: "finance", suggestedMotion: "scale" },
  { name: "QrCode", description: "QR code", category: "finance", suggestedMotion: "scale" },
  { name: "Gift", description: "Gift box", category: "finance", suggestedMotion: "bounce" },
  { name: "PackageBox", description: "Package/shipping box", category: "finance", suggestedMotion: "scale" },
  { name: "Truck", description: "Delivery truck", category: "finance", suggestedMotion: "translate" },
  { name: "PackageCheck", description: "Package delivered", category: "finance", suggestedMotion: "draw" },
]

// ============================================================================
// COMMUNICATION (Target: 70 icons, ~45 new)
// ============================================================================
export const COMMUNICATION: IconSpec[] = [
  { name: "Mail", description: "Email envelope", category: "communication", suggestedMotion: "scale" },
  { name: "MailOpen", description: "Open email", category: "communication", suggestedMotion: "scale" },
  { name: "MailPlus", description: "New email", category: "communication", suggestedMotion: "scale" },
  { name: "MailMinus", description: "Remove email", category: "communication", suggestedMotion: "scale" },
  { name: "MailCheck", description: "Email sent", category: "communication", suggestedMotion: "draw" },
  { name: "MailX", description: "Email error", category: "communication", suggestedMotion: "shake" },
  { name: "MailWarning", description: "Email warning", category: "communication", suggestedMotion: "shake" },
  { name: "MailSearch", description: "Search email", category: "communication", suggestedMotion: "scale" },
  { name: "Inbox", description: "Inbox tray", category: "communication", suggestedMotion: "scale" },
  { name: "Send", description: "Send/paper plane", category: "communication", suggestedMotion: "translate" },
  { name: "SendHorizontal", description: "Send horizontal", category: "communication", suggestedMotion: "translate" },
  { name: "Forward", description: "Forward arrow", category: "communication", suggestedMotion: "translate" },
  { name: "Reply", description: "Reply arrow", category: "communication", suggestedMotion: "translate" },
  { name: "ReplyAll", description: "Reply all arrows", category: "communication", suggestedMotion: "translate" },
  { name: "MessageCircle", description: "Message bubble circle", category: "communication", suggestedMotion: "scale" },
  { name: "MessageSquare", description: "Message bubble square", category: "communication", suggestedMotion: "scale" },
  { name: "MessageSquarePlus", description: "New message", category: "communication", suggestedMotion: "scale" },
  { name: "MessageSquareDot", description: "Unread message", category: "communication", suggestedMotion: "pulse" },
  { name: "MessagesSquare", description: "Multiple messages", category: "communication", suggestedMotion: "scale" },
  { name: "MessageCircleMore", description: "More messages indicator", category: "communication", suggestedMotion: "scale" },
  { name: "AtSign", description: "@ symbol", category: "communication", suggestedMotion: "scale" },
  { name: "Hash", description: "# hashtag", category: "communication", suggestedMotion: "scale" },
  { name: "Phone", description: "Phone", category: "communication", suggestedMotion: "shake" },
  { name: "PhoneCall", description: "Active call", category: "communication", suggestedMotion: "pulse" },
  { name: "PhoneOff", description: "Phone off", category: "communication", suggestedMotion: "scale" },
  { name: "PhoneIncoming", description: "Incoming call", category: "communication", suggestedMotion: "shake" },
  { name: "PhoneOutgoing", description: "Outgoing call", category: "communication", suggestedMotion: "translate" },
  { name: "PhoneMissed", description: "Missed call", category: "communication", suggestedMotion: "shake" },
  { name: "PhoneForwarded", description: "Forwarded call", category: "communication", suggestedMotion: "translate" },
  { name: "VideoCall", description: "Video call camera", category: "communication", suggestedMotion: "scale" },
  { name: "Voicemail", description: "Voicemail icon", category: "communication", suggestedMotion: "scale" },
  { name: "BellIcon", description: "Notification bell", category: "communication", suggestedMotion: "shake" },
  { name: "BellOff", description: "Bell with slash", category: "communication", suggestedMotion: "scale" },
  { name: "BellRing", description: "Ringing bell", category: "communication", suggestedMotion: "shake" },
  { name: "BellDot", description: "Bell with notification dot", category: "communication", suggestedMotion: "pulse" },
  { name: "BellPlus", description: "Add notification", category: "communication", suggestedMotion: "scale" },
  { name: "BellMinus", description: "Remove notification", category: "communication", suggestedMotion: "scale" },
  { name: "Megaphone", description: "Megaphone/announcement", category: "communication", suggestedMotion: "scale" },
  { name: "Rss", description: "RSS feed", category: "communication", suggestedMotion: "pulse" },
  { name: "Podcast2", description: "Podcast mic", category: "communication", suggestedMotion: "pulse" },
  { name: "Broadcast", description: "Broadcasting", category: "communication", suggestedMotion: "pulse" },
  { name: "Signal", description: "Signal strength", category: "communication", suggestedMotion: "pulse" },
  { name: "SignalLow", description: "Low signal", category: "communication", suggestedMotion: "pulse" },
  { name: "SignalZero", description: "No signal", category: "communication", suggestedMotion: "scale" },
  { name: "Wifi", description: "WiFi signal", category: "communication", suggestedMotion: "pulse" },
  { name: "WifiOff", description: "WiFi off", category: "communication", suggestedMotion: "scale" },
  { name: "WifiLow", description: "Weak WiFi", category: "communication", suggestedMotion: "pulse" },
  { name: "Bluetooth", description: "Bluetooth", category: "communication", suggestedMotion: "pulse" },
  { name: "BluetoothOff", description: "Bluetooth off", category: "communication", suggestedMotion: "scale" },
  { name: "BluetoothConnected", description: "Bluetooth connected", category: "communication", suggestedMotion: "pulse" },
  { name: "Nfc", description: "NFC icon", category: "communication", suggestedMotion: "pulse" },
]

// ============================================================================
// ACCESSIBILITY (Target: 30 icons, all new)
// ============================================================================
export const ACCESSIBILITY: IconSpec[] = [
  { name: "Accessibility", description: "Universal accessibility symbol", category: "accessibility", suggestedMotion: "scale" },
  { name: "Wheelchair", description: "Wheelchair user", category: "accessibility", suggestedMotion: "scale" },
  { name: "EarHearing", description: "Ear with hearing waves", category: "accessibility", suggestedMotion: "pulse" },
  { name: "EarOff", description: "Hearing impaired", category: "accessibility", suggestedMotion: "scale" },
  { name: "EyeAccessibility", description: "Vision accessibility", category: "accessibility", suggestedMotion: "scale" },
  { name: "Blind", description: "Blind/visually impaired", category: "accessibility", suggestedMotion: "scale" },
  { name: "Braille", description: "Braille dots", category: "accessibility", suggestedMotion: "scale" },
  { name: "SignLanguage", description: "Sign language hand", category: "accessibility", suggestedMotion: "scale" },
  { name: "ClosedCaptions", description: "CC closed captions", category: "accessibility", suggestedMotion: "scale" },
  { name: "AudioDescription", description: "AD audio description", category: "accessibility", suggestedMotion: "scale" },
  { name: "TextSize", description: "Text size adjustment", category: "accessibility", suggestedMotion: "scale" },
  { name: "TextIncrease", description: "Increase text size", category: "accessibility", suggestedMotion: "scale" },
  { name: "TextDecrease", description: "Decrease text size", category: "accessibility", suggestedMotion: "scale" },
  { name: "Contrast", description: "High contrast", category: "accessibility", suggestedMotion: "scale" },
  { name: "ColorBlind", description: "Color blind mode", category: "accessibility", suggestedMotion: "scale" },
  { name: "ScreenReader", description: "Screen reader", category: "accessibility", suggestedMotion: "scale" },
  { name: "KeyboardNav", description: "Keyboard navigation", category: "accessibility", suggestedMotion: "scale" },
  { name: "FocusRing", description: "Focus indicator", category: "accessibility", suggestedMotion: "pulse" },
  { name: "VoiceControl", description: "Voice control", category: "accessibility", suggestedMotion: "pulse" },
  { name: "SwitchAccess", description: "Switch access", category: "accessibility", suggestedMotion: "scale" },
  { name: "Cognitive", description: "Cognitive accessibility", category: "accessibility", suggestedMotion: "scale" },
  { name: "SimplifiedUi", description: "Simplified interface", category: "accessibility", suggestedMotion: "scale" },
  { name: "MotorImpaired", description: "Motor impairment", category: "accessibility", suggestedMotion: "scale" },
  { name: "AssistiveTech", description: "Assistive technology", category: "accessibility", suggestedMotion: "scale" },
  { name: "EasyRead", description: "Easy read mode", category: "accessibility", suggestedMotion: "scale" },
  { name: "Dyslexia", description: "Dyslexia friendly", category: "accessibility", suggestedMotion: "scale" },
  { name: "ReducedMotion", description: "Reduced motion preference", category: "accessibility", suggestedMotion: "scale" },
  { name: "Timer", description: "Time limit/adjustment", category: "accessibility", suggestedMotion: "rotate" },
  { name: "Pause2", description: "Pause content", category: "accessibility", suggestedMotion: "scale" },
  { name: "GuideLines", description: "Reading guidelines", category: "accessibility", suggestedMotion: "scale" },
]

// ============================================================================
// ALL ICONS COMBINED
// ============================================================================
export const ALL_ICONS: IconSpec[] = [
  ...ARROWS,
  ...UI,
  ...DEVELOPER,
  ...AI,
  ...MEDIA,
  ...SECURITY,
  ...FINANCE,
  ...COMMUNICATION,
  ...ACCESSIBILITY,
]

// Summary
export const ICON_SUMMARY = {
  arrows: ARROWS.length,
  ui: UI.length,
  developer: DEVELOPER.length,
  ai: AI.length,
  media: MEDIA.length,
  security: SECURITY.length,
  finance: FINANCE.length,
  communication: COMMUNICATION.length,
  accessibility: ACCESSIBILITY.length,
  total: ALL_ICONS.length,
}
